<?php

/**
 * 商户API日志
 *
 * @author loren
 */

namespace App\Http\Controllers;

use App\Models\Merchant;
use DB;

class ApiLogsController extends AdminBaseController {

    protected $modelName = 'App\Models\ApiLogs';

    public $customViewPath = 'log';
    public $customViews = ['index'];

    protected function beforeRender() {
        parent::beforeRender();
    }

    protected function customSearchConditions($oQuery, $aParams) {
        $oQuery->selectRaw("*,UNIX_TIMESTAMP(end_time) - UNIX_TIMESTAMP(start_time) as time_length");
        if(isset($aParams['merchant_id']) && $aParams['merchant_id'] != ''){
            $aIds = Merchant::getIdsByName($aParams['merchant_id'],true);
            if(empty($aIds)){
                $oQuery->where('id','=',0);
            }else{
                $oQuery->whereIn('merchant_id',$aIds);
            }

        }
        return parent::customSearchConditions($oQuery, $aParams); // TODO: Change the autogenerated stub
    }

}